Bugfix stratify pretest sample
EpistasisLab/tpot pull request #1004
Opened 2020-01-16 21:30 UTC by kristiankaufmann

#55  What does this PR do?

Fixes an edge case that arises when using tpot on dataset with extreme class imbalance where the pretest sample would cause an error to be thrown since the sample resulted in only one class being represented in the pretest_sample

## Where should the reviewer start?
See the changes in the tpot base with the introduction of a init_pretest function and the corresponding implementation in the TPotClassifier

## How should this PR be tested?
a unit test was added to verify that the pretest function works as intended

## Any background context you want to provide?
see PR description
## Questions:

- Do the docs need to be updated? no
- Does this PR add new (Python) dependencies? no

2020-01-17 01:00 UTC, weixuanfu requested changes
Thank you for finding this issue and submitting this PR. Just one suggestion below for train/test splits in classification. Maybe we could also use that `stratify` param in `train_test_split` for regression. If so, I think the fix will be a little simpler.

2020-01-17 01:00 UTC, weixuanfu commented on tpot/tpot.py
> +        self.pretest_X, _, self.pretest_y, _ = train_test_split(features, target, random_state=self.random_state,
Could you please use `stratify` in `train_test_split` function for this classification? Then maybe the checking below is not needed.

2020-01-17 21:56 UTC, kristiankaufmann commented on tpot/tpot.py
> +        self.pretest_X, _, self.pretest_y, _ = train_test_split(features, target, random_state=self.random_state,
I attempted to use the stratify, but as I discovered it preserves the proportions of the classes. Thus if the sample size is limited to 50 samples and the class proportions more imbalanced than 50:1 then passing the stratify parameter to test train split fails the solve the issue.

2020-01-21 15:52 UTC, weixuanfu commented on tpot/tpot.py
> +        self.pretest_X, _, self.pretest_y, _ = train_test_split(features, target, random_state=self.random_state,
Hmm, thank you for the test. I think we will use the solution in this PR after some test.

2020-05-13 13:25 UTC, weixuanfu commented
Thank you for the PR. I merge this patch for a temp fix.

2020-05-13 13:25 UTC, merged