Deep learning
EpistasisLab/tpot pull request #1025
Opened 2020-02-24 09:01 UTC by adriangb

[please review the [Contribution Guidelines](http://epistasislab.github.io/tpot/contributing/) prior to submitting your pull request. go ahead and delete this line if you've already reviewed said guidelines.]

## What does this PR do?
Attempting to revive #895 while expanding upon it a little to allow for more general integration of `Keras` models into `TPOT`.

The main focus is basic sequential models (`tensorflow.keras.models.Sequential`).

This PR proposes a method of wrapping them to allow parametric generation of deep learning models in `TPOT`. Example classes are created for a classifier, a regressor and a transformer (the latter being the original intent of #895).

This is a _very_ rough proof of concept, but I believe that the versatile functionality of `tensorflow.keras` will allow for fancy stuff like callbacks to be integrated into TPOT's logging, etc.

## Where should the reviewer start?
Please start by looking over the general implementation and API in `deep_learning.py`.
I realize that extensive documentation is needed, I will do that at some point, I'm hoping to get _some_ feedback before I spend a bunch of time on that.

## How should this PR be tested?
I wrote some basic tests. More is needed.

I also _think_ I found a bug in `tensorflow.keras.utils.generic_utils.has_arg` which would be a blocker for this. I submitted a PR (tensorflow/tensorflow#37004) on the `tensorflow` repo, we'll see where that goes. If tests on this PR fail, that's probably why.

I also ran some basic tests comparing the performance of these parametrically generated estimators with some basic Keras tutorials I found, it's about the same if not better.

## What are the relevant issues?
#895 , #809

PS: @chappers, I made a new PR because it's a new branch on my fork. I squashed your commits into a single commit for now, I will make sure you are a co-author if this gets merged.

2020-02-24 10:51 UTC, weixuanfu requested changes
Thank you for submitting this PR. I like this feature and I think it should be merged into TPOT if the performance in computational time and accuracy/score is competitive with other scikit-learn estimators in default TPOT configuration (e.g vs. RandomForestEstimator). Please provide more details about the performance test (with/without GPU) and also the search space of hyperparameters. Regarding the callbacks function from `tensorflow.keras`, it can be integrated later.

2020-02-24 10:51 UTC, weixuanfu commented on tests/test_deep_learning.py
> +from sklearn.neural_network import MLPClassifier, MLPRegressor
Please remove this line since this two seems not to be used in the scripts.

2020-02-24 10:51 UTC, weixuanfu commented on tpot/builtins/deep_learning.py
> +class DeepLearningClassifier(KerasClassifier):
Based on the error [in AppVayor](https://ci.appveyor.com/project/weixuanfu/tpot/builds/31010281), it failed to import tpot due to no tensorflow in the environment. Maybe using `HAS_TENSORFLOW` to determine if those new classes should be created.

2020-02-24 10:51 UTC, weixuanfu commented on tests/test_deep_learning.py
> +    def check(X, X_transformed, embedding_layer_size):
This function is duplicated and please only keep one.

2020-02-24 10:52 UTC, weixuanfu commented on tests/test_deep_learning.py
> +from sklearn.neural_network import MLPClassifier, MLPRegressor
Pleas also fix those failed unit tests in this test scripts.

2020-02-24 16:37 UTC, adriangb commented
Great, thank you for taking a look and pointing some things out. I'll do the following three things as next steps:

1. Fix CI issues
2. Fix comments made above
3. Compare performance and accuracy. The primary comparison will be to `sklearn.neaural_net.MLPClassifier`. I will compare accuracy to other models, but I fully expect this to be a lot slower than classic classifiers. I will probably use [this](https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html) scikit-learn doc as a basepoint for comparison.

2020-02-25 20:49 UTC, adriangb commented
Another update. Although I _was_ able to hack this together to make a `DeepLearningRegressor` class with the exact same API as `MPLClassifier`, there are some bugs and it uses somewhat ugly mixin inheritance patterns. Looking around the `tf.keras` source, I found this PR, which I think would make things a lot cleaner and easier on the `TPOT` side: tensorflow/tensorflow#32533

Hence, I think I am going to focus efforts on reviving that PR and will pause work on this one until then.

2020-02-25 20:49 UTC, closed without merging

2020-02-27 19:51 UTC, adriangb commented
Another comment. Testing performance, I found that for small datasets on my laptops CPU, tensorflow/keras was _considerably_ slower than `sklearn.neural_net`. I think running on any decent GPU, distributed or maybe even a workstation CPU, tensorflow would be much faster, but I really don't have the ability to test that.

2020-09-04 02:20 UTC, adriangb commented
If anyone is interested, this could easily be revived using https://github.com/adriangb/scikeras. MLP example: https://github.com/adriangb/scikeras/blob/master/tests/mlp_models.py