allow both max_time_mins and generations as valid parameters concurre…
EpistasisLab/tpot pull request #941
Opened 2019-10-27 10:35 UTC by jhmenke

Thix PR solves #936 by allowing to independently use generations and max_time_mins to limit the tpot search through using one of the parameters or both.

2019-10-28 15:48 UTC, jhmenke commented
i updated the docstring as well

2019-10-28 16:02 UTC, weixuanfu requested changes
Thank you for this PR.

Please also update the [docstring](https://github.com/EpistasisLab/tpot/blob/v0.10.2/tpot/base.py#L122-L126) and related documentation of generations parameter for the case of `generations=None`.

Also, for the case that `generations=None` AND `max_time_mins=None`, a `ValueError` should be raised for indicating invalid parameter combination. Then a unit test is needed for checking this `ValueError`.

2019-11-02 13:17 UTC, jhmenke commented
I made the appropriate changes.

2019-11-04 15:33 UTC, weixuanfu approved these changes

2019-11-04 16:06 UTC, merged